image: cr.yandex/crp742p3qacifd2hcon2/practice-da:latest

stages:
- init
- run

report_job:
    stage: run
    script:
        - python reports_alerts/report_feed.py
        - python reports_alerts/report_both_services.py
    only:
        refs:
            - schedules
        variables:
            - $SCHEDULE_TYPE == "RUN_REPORTS"

alert_job:
    stage: run
    script:
        - python reports_alerts/alerts.py
    only:
        refs:
            - schedules
        variables:
            - $SCHEDULE_TYPE == "RUN_ALERTS"
